name: default
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # run linters, formatters and unit tests
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run all

  # run action on a clean machine without building to check that it works as expected
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          milliseconds: 1000
